### ISSUE TITLE
Document / facilitate the migration from https://hub.docker.com/r/sailfrog/cypht-docker to https://hub.docker.com/u/cypht

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#1047] opened 2024-05-24 23:46 UTC
https://github.com/cypht-org/cypht-docker/ was the official Docker image builder of [Cypht](https://cypht.org/). It is being replaced:
- [Docker-related code will be part of the main Cypht repository](https://github.com/cypht-org/cypht/pull/1001) so https://github.com/cypht-org/cypht-docker/ will be deprecated.
- https://hub.docker.com/u/cypht will replace https://hub.docker.com/r/sailfrog/cypht-docker as per https://github.com/cypht-org/cypht/issues/1016
- Here is background info: https://github.com/cypht-org/cypht-docker/issues/31

This issue is to track what should be done to facilitate this transition once https://hub.docker.com/u/cypht is working well enough.

As of 2024-05-25, https://hub.docker.com/r/sailfrog/cypht-docker/ is serving up 5 month old code from Cypht master, which is missing a lot of fixes and enhancements compared to Cypht 2.0.x or today's master.

**Comment by marclaporte** [comment] 2024-05-25 00:16
Until https://hub.docker.com/u/cypht is operational, https://hub.docker.com/r/jonocodes/cypht can be used to test https://github.com/cypht-org/cypht/pull/1001

**Comment by jonocodes** [comment] 2024-05-25 00:32
We should probably take down the sailfrog image eventually but I dont think it has to happen for a while.

Once the new image is up in https://hub.docker.com/u/cypht we should update the readme on https://hub.docker.com/r/sailfrog/cypht-docker to point people to the new cypht/cypht image.

**Comment by jonocodes** [comment] 2024-05-25 00:33
Also since I have creds now I can publish something right away to cypht/cypht. I'm just not sure what to tag to use.

**Comment by jonocodes** [comment] 2024-05-25 00:36
Also also we should probably merge this first: https://github.com/cypht-org/cypht/pull/1001

**Comment by marclaporte** [comment] 2024-05-25 00:59
> Also since I have creds now I can publish something right away to cypht/cypht.

Yes, please just go for cypht/cypht

**Comment by marclaporte** [comment] 2024-05-25 01:21
> Preferably someone will 'accept' it before I merge.

Done and merged.

We used to only have master, fewer developers, and all MRs reviewed by Jason Munro (project founder), so master was kept very stable.

But now
- Jason is on a break.
- the community is bigger, more projects are underway.
- [mistakes will be made](https://en.wikipedia.org/wiki/Mistakes_were_made): several junior devs who will make mistakes + senior devs who will work on more complex things, which will also lead to issues.

So I decided we would have stable branches: https://github.com/cypht-org/cypht/wiki/Lifecycle

Thus, it's OK to have some short term mess in master while we figure out things like this.

**Comment by marclaporte** [comment] 2024-05-25 01:30
> I'm just not sure what to tag to use. Maybe it will just be a timestamp or something cryptic so its not yet used. Or perhaps I'll just use 'latest' for now.

I don't enough on how 

> We should probably take down the sailfrog image eventually but I dont think it has to happen for a while.

Agreed. Just put a readme pointing to new location.

**Comment by marclaporte** [comment] 2024-05-25 01:46
> I'm just not sure what to tag to use. Maybe it will just be a timestamp or something cryptic so its not yet used. Or perhaps I'll just use 'latest' for now.

So 'latest' would be Cypht master? Why not call it master?

**Comment by marclaporte** [comment] 2024-05-25 01:55
Oh wow!
- https://vsupalov.com/docker-latest-tag/
- https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375
- https://www.howtogeek.com/devops/understanding-dockers-latest-tag/

**Comment by jonocodes** [comment] 2024-05-25 02:00
> Oh wow!
> 
>     * [vsupalov.com/docker-latest-tag](https://vsupalov.com/docker-latest-tag/)


Ha yes. I was about to post the same article.
Long story short, is 'latest' is not well defined. I would say the same problem is for 'master'. When in 'master' was it made?
I personally try to avoid 'latest' and 'master' altogether when distributing images. And stick to version numbers.

There was talk of a 'nightly', which I think may be more meaningful - that is if it is really nightly.

**Comment by jonocodes** [comment] 2024-05-25 02:07
All that being said I have posted to 'latest' while we figure that out:
https://hub.docker.com/r/cypht/cypht

We can delete that tag if we want, but it will be more clear when a release happens.
By the way, this maybe would be a good time to do a release? Then we can get a real version number in there.

**Comment by marclaporte** [comment] 2024-05-25 02:10
> By the way, this maybe would be a good time to do a release? Then we can get a real version number in there.

Sure! @josaphatim can release 2.0.2 Does he need to do anything different than 2.0.1?

**Comment by marclaporte** [comment] 2024-05-25 02:10
> have posted to 'latest' while we figure that out

+1

**Comment by jonocodes** [comment] 2024-05-25 02:17
> > By the way, this maybe would be a good time to do a release? Then we can get a real version number in there.
> 
> Sure! @josaphatim can release 2.0.2 Does he need to do anything different than 2.0.1?

I hate to nit-pick. But this would be a feature release not a bug fix. So to stick inline with symantic versioning it would be 2.1.0.
But I guess that would mess with the support schedule?

**Comment by marclaporte** [comment] 2024-05-25 02:41
> But I guess that would mess with the support schedule?

No, it wouldn't. 2.1.x will just replace 2.0.x as the supported stable branch.

**Comment by marclaporte** [comment] 2024-05-25 02:58
> I hate to nit-pick. But this would be a feature release not a bug fix. So to stick inline with semantic versioning it would be 2.1.0.

This is a good topic. We set general guidelines, but it's only when it hits reality that we can refine our processes. Thank you. I didn't see this as a new feature because nothing changes for the user. But for an sysadmin, it is significant and they should review the changelog. I am fine to tag it 2.1.0 (And say 2.0.x is EoL)

On a related note, master will soon diverge in a material way from 2.x, by requiring PHP 8.1+:
https://github.com/cypht-org/cypht/pull/1044. So the Docker files will need to diverge as well.

**Comment by marclaporte** [comment] 2024-05-25 13:46
@jonocodes should https://github.com/cypht-org/cypht/pull/1044 be held back?

@josaphatim please release Cypht 2.1.0

**Comment by rodriguezny** [comment] 2024-05-25 14:21
> We should probably take down the sailfrog image eventually but I dont think it has to happen for a while.
> 
> Once the new image is up in https://hub.docker.com/u/cypht we should update the readme on https://hub.docker.com/r/sailfrog/cypht-docker to point people to the new cypht/cypht image.

Yes, we should take it down but I think not now. For the moment we can just update the readme adding a deprecated message and a link to https://hub.docker.com/u/cypht so people will know where the new image lives.

**Comment by rodriguezny** [comment] 2024-05-25 14:29
> All that being said I have posted to 'latest' while we figure that out: https://hub.docker.com/r/cypht/cypht
> 
> We can delete that tag if we want, but it will be more clear when a release happens. By the way, this maybe would be a good time to do a release? Then we can get a real version number in there.

Thanks for the new image posted, we can now update sailfrog image readme to point to https://hub.docker.com/u/cypht.

**Comment by jonocodes** [comment] 2024-05-25 14:42
> @jonocodes should https://github.com/cypht-org/cypht/pull/1044 be held back?

I think it can get merged. Then the first real docker release would be php 8. The docker work will not be hard. Side note: I'm away from computer for a few days. 

But you do need to consider the cypht version. Maybe 2.1.0 is fine for a php upgrade since it does not seem to be a breaking change at this point.

**Comment by jonocodes** [comment] 2024-05-25 14:59
> > I hate to nit-pick. But this would be a feature release not a bug fix. So to stick inline with semantic versioning it would be 2.1.0.
> 
> This is a good topic. We set general guidelines, but it's only when it hits reality that we can refine our processes. Thank you. I didn't see this as a new feature because nothing changes for the user. But for an sysadmin, it is significant and they should review the changelog. I am fine to tag it 2.1.0 (And say 2.0.x is EoL)

It can be a little unintuitive but when I work on projects I favor revving the middle number the most. Thats the default. It's not uncommon that the minor version will update several times a day (ie 2.3.4 to 2.4.0 to 2.5.0)

I reserve the last digit to mean this release only fixes a bug and we don't think it would lead to a regression. It's more of an emergency valve that should not happen often.

**Comment by marclaporte** [comment] 2024-05-25 21:54
> Maybe 2.1.0 is fine for a php upgrade since it does not seem to be a breaking change at this point.

Ok, let's do that. And it will make it easier to backport things from Cypht master to 2.x (which I expect we will do a lot of). I updated: https://github.com/cypht-org/cypht/wiki/Lifecycle

**Comment by marclaporte** [comment] 2024-05-25 22:17
> I reserve the last digit to mean this release only fixes a bug and we don't think it would lead to a regression. It's more of an emergency valve that should not happen often.

That was pretty much my original idea for the general lifecycle except I didn't even plan for the last digit. So I had in mind 2.0, 2.1, 2.2, etc. but 2.0.0, 2.1.0, 2.2.0, etc. is better with the emergency valve as you call it :-)

So we'll very likely get to 2.10.0 before we release 3.0, which is fine!

**Comment by marclaporte** [comment] 2024-05-26 12:40
Also to do: update instructions on https://www.cypht.org/install-2x.html

**Comment by rodriguezny** [comment] 2024-05-26 21:39
> We should probably take down the sailfrog image eventually but I dont think it has to happen for a while.
> 
> Once the new image is up in https://hub.docker.com/u/cypht we should update the readme on https://hub.docker.com/r/sailfrog/cypht-docker to point people to the new cypht/cypht image.

@marclaporte I updated https://hub.docker.com/r/sailfrog/cypht-docker overview. I think you should announce the same on https://app.gitter.im/#/room/#cypht-org_community:gitter.im

**Comment by jonocodes** [comment] 2024-05-26 22:40
OK. Perhaps wait to announce until we have a proper tag in the new repo.

**Comment by marclaporte** [comment] 2024-05-27 00:36
> OK. Perhaps wait to announce until we have a proper tag in the new repo.

ok, I pointed people here so they get latest ststuz

**Comment by rodriguezny** [comment] 2024-05-27 18:13
> Also to do: update instructions on https://www.cypht.org/install-2x.html



> Also to do: update instructions on https://www.cypht.org/install-2x.html

https://github.com/cypht-org/cypht-website/pull/60

**Comment by jonocodes** [comment] 2024-05-28 04:44
Ok, I have created a tag [cypht/cypht:2.0.1](https://hub.docker.com/layers/cypht/cypht/2.0.1/images/sha256-f44c483e59e0c87636aee17864484554da9348f0fe441f3fcd603bd2564ddb1c?tab=layers)
where I backfilled the docker work on top of the 2.0.1 git tag. Then I removed 'latest'. Lets call this the first official tag and go ahead and update docs/announce.
This is a good starting point. Next I need to figure out how to build for ARM.

**Comment by jonocodes** [comment] 2024-05-29 20:47
This updates old references:
https://github.com/cypht-org/cypht/pull/1053

Not sure what the PR review policy before merging is.

**Comment by marclaporte** [comment] 2024-05-29 22:58
> Not sure what the PR review policy before merging is.

In general, let someone else review and merge. But if you are confident it's low risk, you can merge it is yourself.

**Comment by rodriguezny** [comment] 2024-06-13 12:58
> @rodriguezny Can we have a nice logo on https://hub.docker.com/r/cypht/cypht ?

Yes, we can. Let me update it.

**Comment by rodriguezny** [comment] 2024-06-13 14:10
> @rodriguezny Can we have a nice logo on https://hub.docker.com/r/cypht/cypht ?



> @rodriguezny Can we have a nice logo on https://hub.docker.com/r/cypht/cypht ?

Done!

**Comment by marclaporte** [comment] 2024-06-18 16:37
@jonocodes: Can we please have a new tag for https://github.com/cypht-org/cypht/releases/tag/v2.1.0?

Thanks!

**Comment by marclaporte** [comment] 2024-06-18 17:12
@rodriguezny We have 944 stars on https://github.com/cypht-org/cypht but only 2 on https://hub.docker.com/r/cypht/cypht

Any ideas?

**Comment by rodriguezny** [comment] 2024-06-18 17:35
> @rodriguezny We have 944 stars on https://github.com/cypht-org/cypht but only 2 on https://hub.docker.com/r/cypht/cypht
> 
> Any ideas?

I think the fact is that not every github user or every community member has a dockerhub account. In the 2 stars, there is one of mine and the other one should be for @jonocodes or you or any one else. Let's remember community members to give us a star.

**Comment by marclaporte** [comment] 2024-06-18 17:38
Oh! I thought it grabbed the stars from GitHub :-)

**Comment by jonocodes** [comment] 2024-06-18 22:41
> @jonocodes: Can we please have a new tag for [`v2.1.0` (release)](https://github.com/cypht-org/cypht/releases/tag/v2.1.0)? (now requires PHP 8.1)
> 
> Thanks!

Yes, 2.1.0 is now in docker hub.

Also I just added instructions so others know how to do the release:
https://github.com/cypht-org/cypht/wiki/How-to-release-Cypht#manually-releasing-a-docker-image

Side note: I think it would be nice to surface the version number either in the UI or in the HTML source to help with debugging user issues.

**Comment by marclaporte** [comment] 2024-06-19 02:00
> would be nice to surface the version number either in the UI or in the HTML

Done: https://github.com/cypht-org/cypht/pull/594

**Comment by jonocodes** [comment] 2024-06-19 16:35
> > would be nice to surface the version number either in the UI or in the HTML
> 
> Done: #594

I think whats here is a good starting point. But it is focused on development.
a) I dont know how to enable it or where to find it displayed
b) I dont think it will display the tag version. only the checksum
c) I dont think it will work in docker since there is no git there

Ideally this would be shown to all users in production as a version number like 2.1.0

**Comment by marclaporte** [comment] 2024-06-19 16:44
> Ideally this would be shown to all users in production as a version number like 2.1.0

Agreed. Can you please add?

**Comment by jonocodes** [comment] 2024-06-19 16:47
> > Ideally this would be shown to all users in production as a version number like 2.1.0
> 
> Agreed. Can you please add?

Lets make a ticket. It will take some work to sort out.

**Comment by jonocodes** [comment] 2024-06-19 17:06
> > Yes, 2.1.0 is now in docker hub.
> 
> @jonocodes The front page of [hub.docker.com/r/cypht/cypht](https://hub.docker.com/r/cypht/cypht) still mentions PHP 7. Maybe best to remove version number since it can vary?

Updated. And now there are instructions in the wiki
https://github.com/cypht-org/cypht/wiki/How-to-release-Cypht#updating-readme-in-dockerhub

**Comment by marclaporte** [comment] 2024-07-14 12:48
@rodriguezny what is left to do here, if anything?

**Comment by rodriguezny** [comment] 2024-07-14 19:50
> @rodriguezny what is left to do here, if anything?

AFAIK, nothing is left. Unless @jonocodes says other thing.

**Comment by jonocodes** [comment] 2024-07-15 16:35
Looks good to me. Thanks.

**Closed** 2024-07-16 03:41 UTC
